name: Rust

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clippy
        run: for mfst in **/Cargo.toml; do cargo clippy --manifest-path="$mfst"; done

  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Run tests
       run: for mfst in **/Cargo.toml; do cargo test --manifest-path="$mfst"; done
